version: "3.8"

services:
  nasake:
    build: .
    env_file: ./.env
    environment:
      - POSTGRES_HOST=db
    command: uvicorn --reload server.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      # host:container
      - ./:/app/:rw
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nasake

volumes:
  db_data:
